#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Artist
#        - App\Entity\MusicStyle
#        - App\Entity\Song


easy_admin:
    entities:
    # List the entity class name you want to manage
        Song:
            class: App\Entity\Song
            form:
                fields:
                    - name
                    - styles
                    - artists
                    - { property: 'audioFile', label: 'AudioFile', type: 'vich_file', type_options: {required: false, allow_delete: false}}

        Artist :
            class: App\Entity\Artist
        MusicStyle :
            class: App\Entity\MusicStyle

    site_name: 'Music Library'
#    site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />'

    design:

#        brand_color: 'blue'

        menu:
            - { entity: 'Song', icon: 'music' }
            - { entity: 'Artist', icon: 'male' }
            - { entity: 'MusicStyle',label: 'Style', icon: 'globe' }
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@VichUploader/Form/fields.html.twig'
        assets:
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
            js:
                - 'bundles/easyadmin/bootstrap-all.js'


    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
        number: '%.2d'